#------------#
# Lint start #
#------------#
name: MY_LINTER

on:
  push:
    branches: 
      - master

jobs:
  my_testing:
    runs-on: ubuntu-latest
    steps:
    - name: Print greeting
      run: echo "Hello World from Testing Job"

  my_deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Print greeting
      run: echo "Hello World from Deploy Job"
